/**
 * Property Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CurrentMonth {
    tDActiveProp?: number;
    activeProp?: number;
    tDActiveLeases?: number;
    tDVacantProp?: number;
    tDTenancyInArrearsCount?: number;
    tDActiveTenancies?: number;
    tDTenancyArrearsAmount?: number;
    tDTenancyInArrearsPercentage?: number;
    tDVacantPropPercentage?: number;
    mTDNetGainedLostMgmts?: number;
    mTDLostMgmts?: number;
    mTDGainedNonTenantedMgmts?: number;
    mTDGainedTenantedMgmts?: number;
}
